apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: collaboration-notes
data:
  Authentication__Authority: https://auth.davish.net/realms/conotes
  Authentication__Audience: conotes-spa
  OpenTelemetry__OtlpEndpoint: http://signoz-otel-collector.signoz.svc.cluster.local:4318
