<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.OpenApi" />
    <PackageReference Include="Davish.Endpoints" />
    <PackageReference Include="Davish.Result.AspNetCore.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoNotes.Application\CoNotes.Application.csproj" />
    <ProjectReference Include="..\CoNotes.Infrastructure\CoNotes.Infrastructure.csproj" />
    <ProjectReference Include="..\CoNotes.Domain\CoNotes.Domain.csproj" />
  </ItemGroup>

</Project>
